language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4

env:
    global:
        - SETUPTOOLS_VERSION=stable

matrix:
    include:
        - python: 2.7
          env: SETUPTOOLS_VERSION=dev

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8

    # Install conda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

    # Update apt-get listings
    - sudo apt-get update

    # Install dot
    - sudo apt-get install graphviz

install:
    - conda install --yes pip "pytest<2.6" sphinx cython numpy mercurial mock
    - pip install coveralls pytest-cov
    # We cannot install the developer version of setuptools using pip because
    # pip tries to remove the previous version of setuptools before the
    # installation is complete, which causes issues. Instead, we just install
    # setuptools manually.
    - if [[ $SETUPTOOLS_VERSION == dev ]]; then hg clone https://bitbucket.org/pypa/setuptools; cd setuptools; python setup.py install; cd ..; fi

before_script:
    # Some of the tests use git commands that require a user to be configured
    - git config --global user.name "A U Thor"
    - git config --global user.email "author@example.com"

script:
    - py.test --cov astropy_helpers

after_success:
    - coveralls
